server:
  port: 9005 #指定运行端口
logging:
  file:
    name: logs/${spring.cloud.client.ip-address}/${spring.application.name}.log
    path: logs
  level:
    root: INFO
spring:
  application:
    name: vue-dashboard #指定服务名称
  thymeleaf:
    enabled: true
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    check-template-location: true
    mode: HTML
    suffix: .html
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}  #指定主机地址
    instance-id:  ${spring.cloud.client.ip-address} :${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90 #服务失效时间，默认90
    lease-renewal-interval-in-seconds: 30 #服务续约时间，默认30
  client:
    fetch-registry: true #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true #指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
      defaultZone: http://wengjp:wengjp123@wengjp.local:9001/eureka
    registry-fetch-interval-seconds: 30 #从注册中心获取其他服务信息的间隔时间，默认30
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always